/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mustafacoban.swingsiparisapp;

import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.Map;
import java.util.Set;
import javax.swing.JOptionPane;

/**
 *
 * @author shepherd
 */
public class OrderApp extends javax.swing.JFrame {
        Map<String,Integer> siparisler = new LinkedHashMap<String,Integer>();
    /**
     * Creates new form OrderApp
     */
    public OrderApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Iskender = new javax.swing.JCheckBox();
        Beyti = new javax.swing.JCheckBox();
        Salata = new javax.swing.JCheckBox();
        Ayran = new javax.swing.JCheckBox();
        SiparişButon = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sipaiş Uygulaması");

        Iskender.setText("İskender - 15 TL");

        Beyti.setText("Beyti - 12 TL");

        Salata.setText("Salata - 5 TL");

        Ayran.setText("Ayran - 2TL");

        SiparişButon.setText("Siparişleri Göster");
        SiparişButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiparişButonActionPerformed(evt);
            }
        });

        jLabel1.setText("MENÜ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Iskender, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                .addComponent(Beyti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Salata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Ayran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(SiparişButon, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Iskender)
                .addGap(18, 18, 18)
                .addComponent(Beyti)
                .addGap(18, 18, 18)
                .addComponent(Salata)
                .addGap(18, 18, 18)
                .addComponent(Ayran)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(SiparişButon)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void SiparisGoster(){
        String message="";
        int tutar=0;
        
        if(siparisler.isEmpty()){
            message = "Siparişiniz bulunmamaktadır.";
        }
        else{
            message += "-----Siparişler-----\n";
            for(Map.Entry<String,Integer> mustafa : siparisler.entrySet()){
                message += mustafa.getKey() + "\n";
                tutar += mustafa.getValue();
                
                
            }
            message += "Tutar: " + tutar;
        }
        JOptionPane.showMessageDialog(this, message); // mesajımız şuan ki jframe objesinde göstereceğimiz için this dedik.
    }
    
    
    
    private void SiparişButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiparişButonActionPerformed
        if(Iskender.isSelected()){
            siparisler.put("İskender",15);
            
        }
        else{
            siparisler.remove("İskender");
        }
        if(Beyti.isSelected()){
            siparisler.put("Beyti",12);
            
        }
        else{
            siparisler.remove("Beyti");
        }
        if(Salata.isSelected()){
            siparisler.put("Salata",5);
            
        }
        else{
            siparisler.remove("Salata");
        }
        if(Ayran.isSelected()){
            siparisler.put("Ayran",2);
            
        }
        else{
            siparisler.remove("Ayran");
        }
        
        SiparisGoster();
    }//GEN-LAST:event_SiparişButonActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Ayran;
    private javax.swing.JCheckBox Beyti;
    private javax.swing.JCheckBox Iskender;
    private javax.swing.JCheckBox Salata;
    private javax.swing.JButton SiparişButon;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
