/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mustafacoban.swingjpassword;

import javax.swing.JOptionPane;

/**
 *
 * @author shepherd
 */
public class userLogin extends javax.swing.JFrame {

    /**
     * Creates new form userLogin
     */
    public userLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LKullaniciAdi = new javax.swing.JLabel();
        Parola = new javax.swing.JPasswordField();
        LParola = new javax.swing.JLabel();
        Giris = new javax.swing.JButton();
        KullaniciAdi = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LKullaniciAdi.setText("Username :");

        Parola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParolaActionPerformed(evt);
            }
        });

        LParola.setText("Password :");

        Giris.setText("Login");
        Giris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GirisActionPerformed(evt);
            }
        });

        KullaniciAdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KullaniciAdiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LParola, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LKullaniciAdi, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(KullaniciAdi)
                    .addComponent(Parola, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(Giris))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(KullaniciAdi)
                    .addComponent(LKullaniciAdi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Parola)
                    .addComponent(LParola, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(Giris)
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KullaniciAdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KullaniciAdiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KullaniciAdiActionPerformed

    private void ParolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParolaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ParolaActionPerformed

    private void GirisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GirisActionPerformed
        String kullanici_adi = KullaniciAdi.getText();
        String sifre = new String(Parola.getPassword());
        
        String message;
        if(kullanici_adi.equals("Aydın ÇOBAN") && sifre.equals("yavuzlar624")){
            message = "Hosgeldiniz "  + kullanici_adi;
        }
        else if(!kullanici_adi.equals("Aydın ÇOBAN") && sifre.equals("yavuzlar624")){
            message = "Kullanıcı adı hatalı";
        }
        else if(kullanici_adi.equals("Aydın ÇOBAN") && !sifre.equals("yavuzlar624")){
            message = "Parola hatalı";
        }else{
            
            message = "Kullanıcı adı ve Parola hatalı";
        }
        if(message.equals("Hosgeldiniz " + kullanici_adi)){
            //setVisible(false); // pencere görünürlüğünü kapattık.
            JOptionPane.showMessageDialog(this, message);
            System.exit(0); // programı kapatır.
        }
        else{
            JOptionPane.showMessageDialog(this, message);
        }
    
        //JOptionPane.showMessageDialog(this, message); mesaj diyalog
        //Textfielddeki alanı temizlemek için.
        KullaniciAdi.setText("");
        Parola.setText("");
        
        
        
    }//GEN-LAST:event_GirisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Giris;
    private javax.swing.JTextField KullaniciAdi;
    private javax.swing.JLabel LKullaniciAdi;
    private javax.swing.JLabel LParola;
    private javax.swing.JPasswordField Parola;
    // End of variables declaration//GEN-END:variables
}
