/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mustafacoban.swingstockapp;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shepherd
 */
public class StockApp extends javax.swing.JFrame {

    /**
     * Creates new form StockApp
     */
    public StockApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        urun_adi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cb_kategori = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        fiyat = new javax.swing.JTextField();
        mesaj_alani = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        urun_tablosu = new javax.swing.JTable();
        urun_ekle_butonu = new javax.swing.JButton();
        urun_guncelleme = new javax.swing.JButton();
        urun_sil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ürün ismi : ");

        jLabel2.setText("Kategori :");

        cb_kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kültür ve Sanat", "Gıda", "Elektronik" }));

        jLabel3.setText("Fiyat : ");

        mesaj_alani.setForeground(new java.awt.Color(255, 0, 0));

        urun_tablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ürün ismi", "Kategori", "Fiyat"
            }
        ));
        urun_tablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                urun_tablosuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(urun_tablosu);

        urun_ekle_butonu.setText("Ürün Ekle");
        urun_ekle_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urun_ekle_butonuActionPerformed(evt);
            }
        });

        urun_guncelleme.setText("Ürün Güncelle");
        urun_guncelleme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urun_guncellemeActionPerformed(evt);
            }
        });

        urun_sil.setText("Ürün Sil");
        urun_sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urun_silActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(urun_adi)
                                    .addComponent(cb_kategori, 0, 168, Short.MAX_VALUE)
                                    .addComponent(fiyat)))
                            .addComponent(mesaj_alani, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(urun_ekle_butonu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(urun_guncelleme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(urun_sil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 11, Short.MAX_VALUE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(urun_adi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(urun_guncelleme))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_kategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(urun_ekle_butonu))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fiyat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(urun_sil)))
                .addGap(31, 31, 31)
                .addComponent(mesaj_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void urun_ekle_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urun_ekle_butonuActionPerformed
        mesaj_alani.setText("");
        DefaultTableModel model = (DefaultTableModel)urun_tablosu.getModel();
        
        if(urun_adi.getText().trim().equals("")){ // trim erase spaces begin and end of the text.
            mesaj_alani.setText("Ürün ismi boş bırakılmaz....");
        }
        else{
            Object[] eklenecek = {urun_adi.getText(),cb_kategori.getSelectedItem().toString(),fiyat.getText()};
            model.addRow(eklenecek);
        }
    }//GEN-LAST:event_urun_ekle_butonuActionPerformed

    private void urun_guncellemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urun_guncellemeActionPerformed
       mesaj_alani.setText("");
       DefaultTableModel model = (DefaultTableModel)urun_tablosu.getModel();
       
       int secili_row = urun_tablosu.getSelectedRow(); // hangi satırda olduğunu döner. tabloya tıklmazsa -1 döner.
       
       if(secili_row == -1){
           
           if (urun_tablosu.getRowCount() == 0){
               mesaj_alani.setText("Ürün tablosu şu anda boş.....");
           }
           else{
               mesaj_alani.setText("Lütfen güncellenecek ürünü seçin....");
           }
       }
       else{
           model.setValueAt(urun_adi.getText(), secili_row, 0); //(negüncellenecekse, satır,sutün)
           model.setValueAt(cb_kategori.getSelectedItem().toString(), secili_row, 1);
           model.setValueAt(fiyat.getText(),secili_row, 2);
           
           mesaj_alani.setText("Ürün başarıyla güncellendi.");
       }
       
       
    }//GEN-LAST:event_urun_guncellemeActionPerformed

    private void urun_tablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_urun_tablosuMouseClicked
        DefaultTableModel model = (DefaultTableModel) urun_tablosu.getModel();
       
       int secili_row = urun_tablosu.getSelectedRow();
       urun_adi.setText(model.getValueAt(secili_row,0).toString());
       cb_kategori.setSelectedItem(model.getValueAt(secili_row,1).toString());
       fiyat.setText(model.getValueAt(secili_row,2).toString());
    }//GEN-LAST:event_urun_tablosuMouseClicked

    private void urun_silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urun_silActionPerformed
        DefaultTableModel model = (DefaultTableModel) urun_tablosu.getModel();
        int secili_row = urun_tablosu.getSelectedRow();
        mesaj_alani.setText("");
        if(secili_row == -1){
            if(urun_tablosu.getRowCount() == 0){
                mesaj_alani.setText("Ürün tablosu şu anda boş....");
            }
            else{
                mesaj_alani.setText("Lütfen silinecek ürünü seçiniz...");
            }
        }
        else{
            model.removeRow(secili_row);
            mesaj_alani.setText("Ürün başarıyla silindi.");
        }
    }//GEN-LAST:event_urun_silActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StockApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StockApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StockApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StockApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StockApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_kategori;
    private javax.swing.JTextField fiyat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mesaj_alani;
    private javax.swing.JTextField urun_adi;
    private javax.swing.JButton urun_ekle_butonu;
    private javax.swing.JButton urun_guncelleme;
    private javax.swing.JButton urun_sil;
    private javax.swing.JTable urun_tablosu;
    // End of variables declaration//GEN-END:variables
}
